'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Droplets, Heart, Leaf, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, UserRound, X } from 'lucide-react';

const MODEL='https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?auto=format&fit=crop&w=1800&q=88';
const MODEL_CLOSE='https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1600&q=88';
const product={name:'Glow Serum',price:'[Editable price]',size:'[Size]',summary:'A silky, lightweight ritual designed to hydrate and support a soft, naturally radiant complexion.'};

function GlassButton({children,secondary=false,onClick}:{children:React.ReactNode;secondary?:boolean;onClick?:()=>void}){return <button className={`btn ${secondary?'secondary':''}`} onClick={onClick}>{children}<ArrowRight size={16}/></button>}

export default function Home(){
 const [menu,setMenu]=useState(false),[cart,setCart]=useState(false),[qty,setQty]=useState(0),[wish,setWish]=useState(false),[compare,setCompare]=useState(52),[drawer,setDrawer]=useState(false),[email,setEmail]=useState(''),[news,setNews]=useState<'idle'|'loading'|'done'|'error'>('idle');
 const closeRef=useRef<HTMLButtonElement>(null);
 const cartReady=useRef(false);
 useEffect(()=>{const n=Number(localStorage.getItem('lumera-cart')||0);setQty(n);cartReady.current=true},[]);
 useEffect(()=>{if(cartReady.current)localStorage.setItem('lumera-cart',String(qty))},[qty]);
 useEffect(()=>{if(cart||menu||drawer){setTimeout(()=>closeRef.current?.focus(),50); const f=(e:KeyboardEvent)=>e.key==='Escape'&&(setCart(false),setMenu(false),setDrawer(false));document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)}},[cart,menu,drawer]);
 const subscribe=(e:React.FormEvent)=>{e.preventDefault();if(!/^\S+@\S+\.\S+$/.test(email)){setNews('error');return}setNews('loading');setTimeout(()=>setNews('done'),700)};
 return <main>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Product',name:'Glow Serum',brand:{'@type':'Brand',name:'LUMÉRA SKINCARE'},description:product.summary})}}/>
  <a className="skip" href="#content">Skip to content</a><div className="grain" aria-hidden="true"/>
  <header className="nav glass"><Link className="brand" href="#top"><Leaf size={17}/>LUMÉRA <span>SKINCARE</span></Link><nav>{['Shop','Benefits','The Ritual','Ingredients','Our Story','Reviews'].map(x=><a key={x} href={`#${x.toLowerCase().replaceAll(' ','-')}`}>{x}</a>)}</nav><div className="nav-actions"><Link aria-label="Search products" href="/search"><Search/></Link><Link aria-label="Account" href="/account"><UserRound/></Link><button aria-label={`Shopping bag with ${qty} items`} onClick={()=>setCart(true)}><ShoppingBag/><b>{qty}</b></button><button className="mobile-menu" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></button></div></header>
  <section id="top" className="hero"><Image src={MODEL} alt="LUMÉRA muse in warm golden light" fill priority sizes="100vw"/><div className="hero-shade"/><div id="content" className="hero-copy reveal"><p className="eyebrow">LUMÉRA SKINCARE</p><h1>Natural Glow.<br/><em>Real You.</em></h1><p>Meet the daily glow ritual created to hydrate, brighten and reveal skin that still feels beautifully yours.</p><div className="actions"><GlassButton onClick={()=>document.querySelector('#shop')?.scrollIntoView()}>Glow Now</GlassButton><GlassButton secondary onClick={()=>document.querySelector('#the-ritual')?.scrollIntoView()}>Discover the Ritual</GlassButton></div></div><div className="scroll">SCROLL <span/></div>
  </section>
  <section id="shop" className="product section"><div className="product-art glass"><div className="halo"/><div className="box">LUMÉRA<br/><small>SKINCARE</small></div><div className="bottle"><div className="dropper"/><div className="collar"/><div className="flask"><span>LUMÉRA</span><small>GLOW SERUM</small></div></div><div className="pedestal"/></div><div className="product-copy"><p className="eyebrow">THE SIGNATURE RITUAL</p><h2>Glow Serum</h2><p className="script">Brighten. Hydrate. Renew.</p><p className="lede">{product.summary}</p><div className="price">{product.price}<span>{product.size}</span></div><div className="buy-row"><div className="stepper"><button aria-label="Decrease quantity" onClick={()=>setQty(Math.max(0,qty-1))}><Minus/></button><output>{Math.max(1,qty)}</output><button aria-label="Increase quantity" onClick={()=>setQty(qty+1)}><Plus/></button></div><button className="add" onClick={()=>{setQty(Math.max(1,qty+1));setCart(true)}}>Add to Bag <ShoppingBag/></button><button className={`wish ${wish?'active':''}`} aria-label="Add to wishlist" onClick={()=>setWish(!wish)}><Heart fill={wish?'currentColor':'none'}/></button></div><div className="accordions">{['Product details','How to use','Ingredients','Shipping and returns'].map((x,i)=><details key={x}><summary>{x}<ChevronDown/></summary><p>{i===0?product.summary:'[Editable verified product information — replace in CMS before launch.]'}</p></details>)}</div></div></section>
  <section id="benefits" className="section benefits"><div className="center"><p className="eyebrow">YOUR GLOW, IN THREE NOTES</p><h2>What your skin can feel</h2></div><div className="card-grid">{[[Sparkles,'Brightens Skin Tone','Helps improve the appearance of dull and uneven-looking skin.'],[Droplets,'Deep Hydration','Provides comforting moisture for a soft, replenished complexion.'],[Leaf,'Natural Radiance','Supports a fresh glow without a heavy or greasy appearance.']].map(([Icon,t,d]:any)=><article className="benefit glass" key={t}><Icon/><span>0{['Brightens Skin Tone','Deep Hydration','Natural Radiance'].indexOf(t)+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section id="the-ritual" className="drop-section"><div className="portrait"><Image src={MODEL_CLOSE} alt="Woman applying skincare serum to her cheek" fill sizes="(max-width:800px) 100vw, 50vw"/></div><div className="drop-copy"><p className="eyebrow">THE ONE-DROP EXPERIENCE</p><h2>One drop.<br/><em>A brighter you.</em></h2><div className="journey"><i/><div><b>01</b><h3>Nourish</h3><p>A quiet moment, made yours.</p></div><div><b>02</b><h3>Hydrate</h3><p>Comforting moisture meets skin.</p></div><div><b>03</b><h3>Brighten</h3><p>Reveal your natural radiance.</p></div></div></div></section>
  <section className="section ritual"><div><p className="eyebrow">THE RITUAL</p><h2>A ritual your skin will<br/>look forward to.</h2><p className="lede">Slow down. Breathe in. Let each drop become a small act of care.</p></div><div className="steps glass">{['Apply a few drops to clean skin.','Gently press and massage across the face and neck.','Follow with moisturiser and daytime sun protection as appropriate.'].map((s,i)=><div key={s}><b>0{i+1}</b><p>{s}</p></div>)}<footer><span>Silky feel</span><span>Quick absorbing</span><span>Non-sticky</span></footer></div></section>
  <section className="compare section"><div className="center"><p className="eyebrow">RADIANCE, REVEALED</p><h2>Glow that feels like you.</h2></div><div className="comparison" style={{'--position':`${compare}%`} as React.CSSProperties}><Image className="before" src={MODEL_CLOSE} alt="Before using Glow Serum demonstration" fill sizes="90vw"/><div className="after"><Image src={MODEL_CLOSE} alt="After using Glow Serum demonstration" fill sizes="90vw"/></div><span className="label before-label">Before</span><span className="label after-label">After</span><input aria-label="Before and after comparison" type="range" min="10" max="90" value={compare} onChange={e=>setCompare(+e.target.value)}/><div className="handle">↔</div></div><p className="note">Visual demonstration only. Individual results may vary.</p></section>
  <section id="ingredients" className="ingredients section"><div><p className="eyebrow">INSIDE THE RITUAL</p><h2>Thoughtfully considered.<br/><em>Beautifully simple.</em></h2><p className="lede">Ingredient content below is structured for your verified formula and must be replaced before launch.</p><button className="text-link" onClick={()=>setDrawer(true)}>View Full Ingredient List <ArrowRight/></button></div><div className="ingredient-grid">{['Hero Ingredient 01','Hydration Complex','Botanical Extract','Antioxidant Support'].map((x,i)=><article className="glass" key={x}><small>CMS PLACEHOLDER · 0{i+1}</small><h3>{x}</h3><p>[Replace with verified ingredient information and approved benefit copy.]</p></article>)}</div></section>
  <section className="promise"><p className="eyebrow">OUR PROMISE</p><div>{[[Sparkles,'Clean Formula'],[Heart,'Cruelty-Free'],[Leaf,'Made for a Brighter You']].map(([Icon,t]:any)=><article key={t}><Icon/><h3>{t}</h3>{t!=='Made for a Brighter You'&&<small>Pending brand-owner verification</small>}</article>)}</div></section>
  <section id="our-story" className="campaign"><Image src={MODEL} alt="LUMÉRA campaign muse holding her skincare ritual" fill sizes="100vw"/><div className="campaign-copy glass"><p className="eyebrow">A MOMENT FOR YOU</p><h2>Self-care looks<br/>good on you.</h2><p>Your glow does not need to look like anyone else’s. LUMÉRA is a simple moment of care for skin that feels hydrated, comfortable and naturally radiant.</p><span className="script">your glow, your way</span></div></section>
  <section id="reviews" className="reviews section"><div className="review-panel glass"><div><p className="eyebrow">THE LUMÉRA CIRCLE</p><h2>Notes from<br/>our community.</h2><div className="rating">— <span>/ 5</span></div><small>Demonstration review module — no ratings published yet.</small></div><div className="review-empty"><Sparkles/><h3>Your story could begin here.</h3><p>Verified customer reviews will appear after launch. No demonstration content is presented as a real testimonial.</p><div className="chips"><button>All skin types</button><button>Dry</button><button>Combination</button></div><button className="btn secondary">Write a Review <ArrowRight/></button></div></div></section>
  <section className="newsletter"><p className="eyebrow">PRIVATE NOTES FROM LUMÉRA</p><h2>Let your glow arrive first.</h2><p>Receive rituals, product updates and thoughtful notes from LUMÉRA.</p><form onSubmit={subscribe} noValidate><label className="sr-only" htmlFor="email">Email address</label><input id="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address"/><button disabled={news==='loading'}>{news==='loading'?'Joining…':'Join the list'} <ArrowRight/></button></form><div className={`form-status ${news}`}>{news==='done'&&'Welcome to the LUMÉRA circle.'}{news==='error'&&'Please enter a valid email address.'}</div><small>By subscribing, you agree to receive marketing emails. You can unsubscribe at any time. See our Privacy Policy.</small></section>
  <footer className="footer"><div className="footer-brand"><Leaf/><b>LUMÉRA</b><span>SKINCARE</span><p>Natural Glow. Real You.</p></div><div className="footer-links">{['Shop','About','Contact','FAQ','Shipping and Returns','Privacy Policy','Terms','Instagram','Pinterest'].map(x=><a href="#" key={x}>{x}</a>)}</div><div className="selectors"><button>Country · [Select] <ChevronDown/></button><button>Currency · [Select] <ChevronDown/></button><p>[Customer support email]<br/>[Support hours]</p></div><div className="signoff">“Glow that feels like you.” — LUMÉRA ♡</div></footer>
  <div className="mobile-buy glass"><div><small>Glow Serum</small><b>{product.price}</b></div><button onClick={()=>{setQty(Math.max(1,qty+1));setCart(true)}}>Add to Bag</button></div>
  {(cart||menu||drawer)&&<div className="overlay" onMouseDown={()=>{setCart(false);setMenu(false);setDrawer(false)}}><aside className="sheet glass" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label={cart?'Shopping bag':menu?'Menu':'Ingredient list'}><button ref={closeRef} className="close" aria-label="Close" onClick={()=>{setCart(false);setMenu(false);setDrawer(false)}}><X/></button>{cart?<><p className="eyebrow">YOUR BAG · {qty}</p><h2>A little glow,<br/>on its way.</h2>{qty?<div className="cart-item"><div className="mini-bottle"/><div><h3>Glow Serum</h3><p>{product.size} · {product.price}</p><div className="stepper"><button onClick={()=>setQty(Math.max(0,qty-1))}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus/></button></div></div></div>:<div className="empty"><ShoppingBag/><p>Your bag is waiting for a little radiance.</p></div>}<div className="coupon"><input placeholder="Coupon code"/><button>Apply</button></div><div className="subtotal"><span>Subtotal</span><b>{qty?product.price:'—'}</b><small>Shipping calculated at checkout.</small></div><Link className={`checkout ${qty?'':'disabled'}`} href={qty?'/checkout':'#'}>Secure test checkout <ArrowRight/></Link><button className="remove" onClick={()=>setQty(0)}>Remove item</button></>:menu?<><p className="eyebrow">MENU</p>{['Shop','Benefits','The Ritual','Ingredients','Our Story','Reviews'].map(x=><a className="menu-link" onClick={()=>setMenu(false)} key={x} href={`#${x.toLowerCase().replaceAll(' ','-')}`}>{x}</a>)}<Link className="menu-link" href="/account">Account</Link></>:<><p className="eyebrow">INGREDIENT TRANSPARENCY</p><h2>Full Ingredient List</h2><div className="placeholder"><b>CMS placeholder</b><p>The verified INCI ingredient list has not yet been supplied. Replace this content in the product data layer before publication.</p></div></>}</aside></div>}
  <div className="progress" aria-hidden="true"/>
  <div className="sr-only" aria-live="polite">Shopping bag updated. {qty} items.</div>
 </main>
}
